version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
    - 2181:2181
    networks:
    - insight
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
        KAFKA_ADVERTISED_HOST_NAME: ${IP}
        KAFKA_ADVERTISED_PORT: 8092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "topicgoogle:1:1, topicscrapython:1:1"
    ports:
    - 8092:9092
    networks:
    - insight
networks:
  insight:
    external: true