version: '3'
services:
    #BROKER
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
        - 2181:2181
    kafka: 
        image: wurstmeister/kafka:latest
        container_name: kafka
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "${ipkafka}"
            KAFKA_ADVERTISED_PORT: 8092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "housToGoogle:1:1,housToTwit:1:1,housToTravel:1:1,housToCompara:1:1,urlToScrapy:1:1,googleToTwit:1:1,textToNER:1:1,tweetToColissi:1:1,tweetToCrousti:1:1,ggimgToColissi:1:1,locToColissi:1:1,bioToColissi:1:1,orgaToColissi:1:1,mediaToColissi:1:1,scrapyToCompara:1:1,comparaToColissi:1:1"
        ports:
    #INDEX
    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.4.2
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            - "ELASTICSEARCH_URL=http://elasticsearch:9200"
        networks:
            - insight
    insight-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
        container_name: elasticsearch
        environment:
            - network.host=0.0.0.0
            - discovery.type=single-node
            - cluster.name=insight
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - insight
networks:
    insight:
        external: true
