version: '3'
services:
  colissithon:
    image: reachhubcorp/colissithon:latest
      container_name: colissithon
      ports:
        - "9876:9876"
      environment:
        INSIGHT_IP: "${ipinsight}"
        INSIGHT_PORT: 8080
        KAFKA_IP: "${ipkafka}"
        KAFKA_PORT: 8092
        COLISSITHON_PORT: 9876
        FROM_COMPARATHON_PICTURES: ggimgToColissi
        FROM_COMPARATHON_HIT: comparaToColissi
        DEBUG_LEVEL: INFO
  housthon:
    image: reachhubcorp/housthon:latest
    container_name: housthon
    environment:
      HOUSTHON_PORT: 8090
      COLISSITHON_IP: "${ipcolissithon}"
      COLISSITHON_PORT: 9876
      KAFKA_IP: "${ipkafka}"
      KAFKA_PORT: 8092
      TOPIC_GOOGLETHON: housToGoogle
      FTP_IP: "${ftpip}"
      FTP_PORT: 21
      FTP_ID: ${ftpid}
      FTP_PASSWORD: ${ftppassword}
      FTP_PATH: ${ftppath}
      PATH_PICTURES: /app/samples/pictures
    ports:
      - "8090:8090"
  selenium-firefox: #TODO à lancer avant googlethon
    restart: always
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  googlethon:
    image: reachhubcorp/googlethon:latest
    container_name: googlethon
    ports:
      - "2223:2223"
    environment:
      KAFKA_IP: "${ipkafka}"
      KAFKA_PORT: 8092
      NUMBER_RESULT: 10
      TOPIC_IN: housToGoogle
      TOPIC_OUT_SCRAPY: urlToScrapy
      DEBUG: INFO
      SEARCH_TYPE: SearchResult
      REMOTE_FIREFOX_IP: ${ipremotefirefox}
      REMOTE_FIREFOX_PORT: ${portremotefirefox}
  comparathon:
    image: reachhubcorp/comparathon:latest
    ports:
      - "9123:9123"
    environment:
      KAFKA_IP: "${ipkafka}"
      KAFKA_PORT: 8092
      TOPIC_TO_CONSUME: scrapyToCompara
      TOPIC_TO_FILL_PICTURES: ggimgToColissi
      TOPIC_TO_FILL_HIT: comparaToColissi
      DEBUG_LEVEL: INFO
      TOLERANCE: 0.6
  scrapython:
    image: reachhubcorp/scrapython:latest
    container_name: scrapython
    environment:
      KAFKA_IP: "${ipkafka}"
      KAFKA_PORT: 8092
      DEPTH: 1
      TOPIC_IN: urlToScrapy
      TOPIC_OUT_COMPARA: scrapyToCompara
      TOPIC_OUT_GOOGLETHON: housToGoogle
      DICO_IP: "${dicoip}"
      DICO_PORT: "${dicoport}"
      DICO_PATH: "${dicopath}"
      DEBUG_LEVEL: INFO
      ES_IP: "${esip}"
  #BROKER
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - insight
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${ipkafka}"
      KAFKA_ADVERTISED_PORT: 8092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "housToGoogle:1:1,housToTwit:1:1,housToTravel:1:1,housToCompara:1:1,urlToScrapy:1:1,googleToTwit:1:1,textToNER:1:1,tweetToColissi:1:1,tweetToCrousti:1:1,ggimgToColissi:1:1,locToColissi:1:1,bioToColissi:1:1,orgaToColissi:1:1,mediaToColissi:1:1,scrapyToCompara:1:1,comparaToColissi:1:1"
    ports:
      - 8092:9092
    networks:
      - insight
  #INDEX
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - insight
  insight-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=insight
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - insight
networks:
  insight:
    external: true