version: '3'
services:
    #HOUSTHON
    housthon:
        image: reachhubcorp/housthon:latest
        container_name: housthon
        environment:
          COLISSITHON_IP: "${ipcolissithon}"
          COLISSITHON_PORT: 9876
          HOUSTHON_PORT: 8090
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          TOPIC_TWITTHON: housToTwit
          TOPIC_TRAVELTHON: housToTravel
          TOPIC_GOOGLETHON: housToGoogle
          TOPIC_COMPARATHON: housToCompara
          PATH_TWEET: /app/samples/tweets
          PATH_PICTURES: /app/samples/pictures
        ports:
        - "8090:8090"
    #COLISSITHON
    colissithon:
        image: reachhubcorp/colissithon:latest
        container_name: colissithon
        ports:
        - "9876:9876"
        environment:
          INSIGHT_IP: "${ipinsight}"
          INSIGHT_PORT: 8080
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          COLISSITHON_PORT: 9876
          FROM_TRAVELTHON: locToColissi
          FROM_COMPARATHON: ggimgToColissi
          FROM_TWEETHON: tweetToColissi
          FROM_CROUSTIBATCH: tweetToCrousti
          DEBUG_LEVEL: INFO
    #TRAVELTHON
    travelthon:
        image: reachhubcorp/travelthon:latest
        container_name: travelthon
        environment:
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          GEOTROUVETHON_IP: "${ipgeotrouvethon}"
          GEOTROUVETHON_PORT: 9966
          TOPIC_IN: housToTravel
          TOPIC_OUT: locToColissi
          DEBUG_LEVEL: INFO
    #TWITTHON
    twitthon:
        image: reachhubcorp/twitthon:latest
        container_name: twitthon
        environment:
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          TOPIC_IN: housToTwit
          TOPICTWEET_OUT: tweetToColissi
          TOPICTMEDIA_OUT: tweetToCrousti
          TOPICTWEET_OUTDEUX: textToNER
          OUTPUTTWEET_USER: /app/timeline/json
          OUTPUTMEDIA_USER: /app/timeline/media
          OUTPUTTWEET_KEYWORDS: /app/keywords/json
          OUTPUTMEDIA_KEYWORDS: /app/keywords/media
          LIMIT: 50
          DEBUG_LEVEL: INFO
    #GEOTROUVETHON
    geotrouvethon:
        image: reachhubcorp/geotrouvethon:latest
        container_name: geotrouvethon
        ports:
        - "9966:9966"
        environment:
          GEOTROUVETHON_PORT: 9966
          GEOTROUVETHON_URL: 0.0.0.0
    wrapper:
        image: cwolff/opener-docker-wrapper
        environment:
            SANIC_OPENER_IDENTIFY_LANGUAGE_URL: http://language_identifier
            SANIC_OPENER_TOKENIZE_URL: http://tokenizer
            SANIC_OPENER_POS_URL: http://pos_tagger
            SANIC_OPENER_NER_URL: http://ner
            SANIC_OPENER_KAF2JSON_URL: http://kaf2json
        ports:
        - 9999:80
        depends_on:
        - language_identifier
        - tokenizer
        - pos_tagger
        - ner
        - kaf2json
    language_identifier:
        image: cwolff/opener-docker-language-identifier
    tokenizer:
        image: cwolff/opener-docker-tokenizer
    pos_tagger:
        image: cwolff/opener-docker-pos-tagger
    ner:
        image: cwolff/opener-docker-ner
    kaf2json:
        image: cwolff/opener-docker-kaf2json
    #NERDETECTHON
    nerdetecthon:
        image: reachhubcorp/nerdetecthon:latest
        container_name: nerdetecthon
        environment:
          SPRING_MAIN_WEB_APPLICATION_TYPE: none
          SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "${ipkafka}:8092"
          SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES: zookeeper
          SPRING_CLOUD_STREAM_BINDINGS_INPUT_BINDER: kafka
          SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION: textToNER
          SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_BINDER: kafka
          SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION: bioToColissi
          FORMAT: dd/MM/YYYY hh:mm:ss
          FIXED_DELAY: 3000
          URLNER: http://wrapper:80/opener
          URLINSIGHT: "http://${ipinsight}:8080/api/"
          URLGEOTROUVETHON: "http://${ipgeotrouvethon}:9966/locate/"
          NER: 'true'
          MOCK: 'false'
          JAVA_OPTS:  -Xmx2048m -Xms256m
          GRAPH_ENABLED: 'true'
          GRAPH_HOST: "http://${ipinsight}:8080/api/"
          ELASTICSEARCH_ENABLED: 'true'
          ELASTICSEARCH_INDEX_NAME: gazetter
          ELASTICSEARCH_HOST: "${ipelasticsearch}"
          ELASTICSEARCH_PORT: 9200
          ELASTICSEARCH_NODE_PORT: 9300
          ELASTICSEARCH_CLUSTERNAME: insight
    #COMPARATHON
    comparathon:
        image: reachhubcorp/comparathon:latest
        ports:
        - "9123:9123"
        container_name: comparathon
        environment:
          PICTURES_NUMBER_TO_DOWNLOAD: 80
          DEBUG_LEVEL : INFO
          TOLERANCE : 0.6
          TOPIC_TO_FILL_PICTURES : ggimgToColissi
          TOPIC_TO_CONSUME : housToCompara
          TOPIC_TO_FILL_URLS : urlToScrapy
          KAFKA_IP : "${ipkafka}"
          KAFKA_PORT : 8092
    #GOOGLETHON
    googlethon:
        image: reachhubcorp/googlethon:latest
        container_name: googlethon
        ports:
        - "2223:2223"
        environment:
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          NUMBER_RESULT: 10
          STANDARD: Vrai
          TOPIC_IN: housToGoogle
          TOPIC_OUT_SCRAPY: urlToScrapy
          DEBUG: INFO
    #SCRAPYTHON
    scrapython:
        image: reachhubcorp/scrapython:latest
        container_name: scrapython
        environment:
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          COMPLEXITY: 1
          TOPIC_IN: urlToScrapy
          TOPIC_OUT: textToNER
          DEBUG_LEVEL: INFO
