version: '3'
services:
    #BROKER
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
        - 2181:2181
    kafka: 
        image: wurstmeister/kafka:latest
        container_name: kafka
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.0.31
            KAFKA_ADVERTISED_PORT: 8092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "housToGoogle:1:1,housToTwit:1:1,housToTravel:1:1,housToCompara:1:1,urlToScrapy:1:1,googleToTwit:1:1,textToNER:1:1,tweetToColissi:1:1,tweetToCrousti:1:1,ggimgToColissi:1:1,locToColissi:1:1,bioToColissi:1:1,orgaToColissi:1:1,mediaToColissi:1:1"
        ports:
        - 8092:9092
    #HOUSTHON
    housthon:
        image: reachhubcorp/housthon:latest
        container_name: housthon
        environment:
          COLISSITHON_IP: 192.168.0.31
          COLISSITHON_PORT: 9876
          HOUSTHON_PORT: 8097
          KAFKA_IP: 192.168.0.31
          KAFKA_PORT: 8092
          TOPIC_GOOGLETHON : housToGoogle
          TOPIC_TWITTHON: housToTwit
          TOPIC_TRAVELTHON: housToTravel
          TOPIC_COMPARATHON: housToCompara
          PATH_TWEET: /app/samples/tweets
          PATH_PICTURES: /app/samples/pictures
        ports:
        - "8097:8097"
    #COLISSITHON
    colissithon:
        image: reachhubcorp/colissithon:latest
        container_name: colissithon
        ports:
            - "9876:9876"
        environment:
            - INSIGHT_IP=192.168.0.31
            - INSIGHT_PORT=8080
            - KAFKA_IP=192.168.0.31
            - KAFKA_PORT=8092
            - COLISSITHON_PORT=9876
            - FROM_TRAVELTHON=locToColissi
            - FROM_COMPARATHON=ggimgToColissi
            - FROM_TWEETHON=tweetToColissi
            - DEBUG_LEVEL=INFO
    #TRAVELTHON
    travelthon:
    	image: reachhubcorp/travelthon:latest
    	container_name: travelthon
    	environment:
          KAFKA_IP: 192.168.0.31
          KAFKA_PORT: 8092
          GEOTROUVETHON_IP: 192.168.0.31
          GEOTROUVETHON_PORT: 9966
          TOPIC_IN: housToTravel
          TOPIC_OUT: locToColissi
          DEBUG_LEVEL: INFO



