version: '3'
services:
    #BROKER
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
        - 2181:2181
        networks:
        - reach
    kafka:docker 
        image: wurstmeister/kafka:latest
        container_name: kafka
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.0.50
            KAFKA_ADVERTISED_PORT: 8092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "googlethon_in:1:1,googlethon_out:1:1,travelthon_in:1:1,travelthon_out:1:1,comparathon_in:1:1,comparathon_out:1:1,tweethon_in:1:1,tweethon_out:1:1"
        ports:
        - 8092:9092
        networks:
        - reach
    #REACH
    colissithon:
        build:
            context: ./context/
        image: reachhubcorp/colissithon:latest
        container_name: colissithon
        ports:
            - "9876:9876"
        environment:
            - INSIGHT_IP=192.168.0.30
            - INSIGHT_PORT=8080
            - KAFKA_IP=192.168.0.50
            - KAFKA_PORT=8092
            - COLISSITHON_PORT=9876
            - FROM_TRAVELTHON=travelthon_out
            - FROM_COMPARATHON=comparathon_out
            - FROM_TWEETHON=tweethon_out
            - DEBUG_LEVEL=INFO
        networks:
        - reach
    
networks:
    reach:
        driver: bridge
